CRITICAL - 2023-12-28 11:10:03 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 227.
 1 SYSTEMPATH\CodeIgniter.php(227): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(191): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-12-28 11:11:21 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 227.
 1 SYSTEMPATH\CodeIgniter.php(227): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(191): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-12-28 11:11:22 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 227.
 1 SYSTEMPATH\CodeIgniter.php(227): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(191): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-12-28 11:11:28 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 227.
 1 SYSTEMPATH\CodeIgniter.php(227): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(191): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-12-28 12:42:44 --> Undefined variable $articulo
in APPPATH\Views\Index.php on line 65.
 1 APPPATH\Views\Index.php(65): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $articulo', 'C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php', 65)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('Index.php', [], true)
 5 APPPATH\Controllers\Home.php(9): view('Index.php')
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-28 12:42:52 --> Undefined variable $articulo
in APPPATH\Views\Index.php on line 65.
 1 APPPATH\Views\Index.php(65): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $articulo', 'C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php', 65)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('Index.php', [], true)
 5 APPPATH\Controllers\Home.php(9): view('Index.php')
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-28 12:43:15 --> Undefined variable $articulo
in APPPATH\Views\Index.php on line 65.
 1 APPPATH\Views\Index.php(65): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $articulo', 'C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php', 65)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('Index.php', [], true)
 5 APPPATH\Controllers\Home.php(9): view('Index.php')
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-28 12:43:24 --> Undefined variable $articulo
in APPPATH\Views\Index.php on line 65.
 1 APPPATH\Views\Index.php(65): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $articulo', 'C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php', 65)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('Index.php', [], true)
 5 APPPATH\Controllers\Home.php(9): view('Index.php')
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-28 12:44:06 --> Undefined variable $articulo
in APPPATH\Views\Index.php on line 65.
 1 APPPATH\Views\Index.php(65): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $articulo', 'C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php', 65)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('Index.php', [], true)
 5 APPPATH\Controllers\Home.php(9): view('Index.php')
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-28 12:44:07 --> Undefined variable $articulo
in APPPATH\Views\Index.php on line 65.
 1 APPPATH\Views\Index.php(65): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $articulo', 'C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php', 65)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('Index.php', [], true)
 5 APPPATH\Controllers\Home.php(9): view('Index.php')
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-28 12:45:44 --> Undefined variable $articulo
in APPPATH\Views\Index.php on line 65.
 1 APPPATH\Views\Index.php(65): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $articulo', 'C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php', 65)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('Index.php', [], true)
 5 APPPATH\Controllers\Home.php(9): view('Index.php')
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-28 12:45:44 --> Undefined variable $articulo
in APPPATH\Views\Index.php on line 65.
 1 APPPATH\Views\Index.php(65): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $articulo', 'C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php', 65)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('Index.php', [], true)
 5 APPPATH\Controllers\Home.php(9): view('Index.php')
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-28 12:45:45 --> Undefined variable $articulo
in APPPATH\Views\Index.php on line 65.
 1 APPPATH\Views\Index.php(65): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $articulo', 'C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php', 65)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('Index.php', [], true)
 5 APPPATH\Controllers\Home.php(9): view('Index.php')
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-28 12:45:45 --> Undefined variable $articulo
in APPPATH\Views\Index.php on line 65.
 1 APPPATH\Views\Index.php(65): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $articulo', 'C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php', 65)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('Index.php', [], true)
 5 APPPATH\Controllers\Home.php(9): view('Index.php')
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-28 12:45:45 --> Undefined variable $articulo
in APPPATH\Views\Index.php on line 65.
 1 APPPATH\Views\Index.php(65): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $articulo', 'C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php', 65)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('Index.php', [], true)
 5 APPPATH\Controllers\Home.php(9): view('Index.php')
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-28 12:45:45 --> Undefined variable $articulo
in APPPATH\Views\Index.php on line 65.
 1 APPPATH\Views\Index.php(65): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $articulo', 'C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php', 65)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('Index.php', [], true)
 5 APPPATH\Controllers\Home.php(9): view('Index.php')
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-28 12:46:30 --> Undefined variable $articulo
in APPPATH\Views\Index.php on line 65.
 1 APPPATH\Views\Index.php(65): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $articulo', 'C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php', 65)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('Index.php', [], true)
 5 APPPATH\Controllers\Home.php(9): view('Index.php')
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-28 12:46:30 --> Undefined variable $articulo
in APPPATH\Views\Index.php on line 65.
 1 APPPATH\Views\Index.php(65): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $articulo', 'C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php', 65)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('Index.php', [], true)
 5 APPPATH\Controllers\Home.php(9): view('Index.php')
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-28 12:46:31 --> Undefined variable $articulo
in APPPATH\Views\Index.php on line 65.
 1 APPPATH\Views\Index.php(65): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $articulo', 'C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php', 65)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('Index.php', [], true)
 5 APPPATH\Controllers\Home.php(9): view('Index.php')
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-28 12:46:31 --> Undefined variable $articulo
in APPPATH\Views\Index.php on line 65.
 1 APPPATH\Views\Index.php(65): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $articulo', 'C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php', 65)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('Index.php', [], true)
 5 APPPATH\Controllers\Home.php(9): view('Index.php')
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-28 12:46:31 --> Undefined variable $articulo
in APPPATH\Views\Index.php on line 65.
 1 APPPATH\Views\Index.php(65): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $articulo', 'C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php', 65)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('Index.php', [], true)
 5 APPPATH\Controllers\Home.php(9): view('Index.php')
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-28 12:46:31 --> Undefined variable $articulo
in APPPATH\Views\Index.php on line 65.
 1 APPPATH\Views\Index.php(65): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $articulo', 'C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php', 65)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('Index.php', [], true)
 5 APPPATH\Controllers\Home.php(9): view('Index.php')
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-28 12:46:31 --> Undefined variable $articulo
in APPPATH\Views\Index.php on line 65.
 1 APPPATH\Views\Index.php(65): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $articulo', 'C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php', 65)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('Index.php', [], true)
 5 APPPATH\Controllers\Home.php(9): view('Index.php')
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-28 12:46:31 --> Undefined variable $articulo
in APPPATH\Views\Index.php on line 65.
 1 APPPATH\Views\Index.php(65): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $articulo', 'C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php', 65)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('Index.php', [], true)
 5 APPPATH\Controllers\Home.php(9): view('Index.php')
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-28 12:46:32 --> Undefined variable $articulo
in APPPATH\Views\Index.php on line 65.
 1 APPPATH\Views\Index.php(65): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $articulo', 'C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php', 65)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\MercadilloElGitanillo\\MercadilloGitanillo\\app\\Views\\Index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('Index.php', [], true)
 5 APPPATH\Controllers\Home.php(9): view('Index.php')
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-28 14:28:16 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'mercadilloGitan...', 3306, '', 0)
#1 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Models\Modelo.php(7): CodeIgniter\Database\BaseConnection->query('SELECT cod_usua...')
#4 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Controllers\Home.php(21): App\models\Modelo->existe('pablo@gmail.com', 'pablo')
#5 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(932): App\Controllers\Home->comprueba()
#6 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Models\Modelo.php(7): CodeIgniter\Database\BaseConnection->query('SELECT cod_usua...')
#3 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Controllers\Home.php(21): App\models\Modelo->existe('pablo@gmail.com', 'pablo')
#4 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(932): App\Controllers\Home->comprueba()
#5 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-12-28 14:28:16 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\Modelo.php(7): CodeIgniter\Database\BaseConnection->query('SELECT cod_usuario,nombre FROM usuarios WHERE correo =\'pablo@gmail.com\' and contrasena= \'pablo\'')
 3 APPPATH\Controllers\Home.php(21): App\models\Modelo->existe('pablo@gmail.com', 'pablo')
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->comprueba()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-28 14:52:59 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'mercadilloGitan...', 3306, '', 0)
#1 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Models\Modelo.php(7): CodeIgniter\Database\BaseConnection->query('SELECT cod_usua...')
#4 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Controllers\Home.php(21): App\models\Modelo->existe('pablo@gmail.com', 'pablo')
#5 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(932): App\Controllers\Home->comprueba()
#6 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Models\Modelo.php(7): CodeIgniter\Database\BaseConnection->query('SELECT cod_usua...')
#3 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Controllers\Home.php(21): App\models\Modelo->existe('pablo@gmail.com', 'pablo')
#4 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(932): App\Controllers\Home->comprueba()
#5 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-12-28 14:52:59 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\Modelo.php(7): CodeIgniter\Database\BaseConnection->query('SELECT cod_usuario,nombre FROM usuarios WHERE correo =\'pablo@gmail.com\' and contrasena= \'pablo\'')
 3 APPPATH\Controllers\Home.php(21): App\models\Modelo->existe('pablo@gmail.com', 'pablo')
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->comprueba()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-28 15:03:56 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'mercadilloGitan...', 3306, '', 0)
#1 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Models\Modelo.php(7): CodeIgniter\Database\BaseConnection->query('SELECT cod_usua...')
#4 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Controllers\Home.php(21): App\models\Modelo->existe('pablo@gmail.com', 'pablo')
#5 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(932): App\Controllers\Home->comprueba()
#6 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Models\Modelo.php(7): CodeIgniter\Database\BaseConnection->query('SELECT cod_usua...')
#3 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Controllers\Home.php(21): App\models\Modelo->existe('pablo@gmail.com', 'pablo')
#4 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(932): App\Controllers\Home->comprueba()
#5 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-12-28 15:03:56 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\Modelo.php(7): CodeIgniter\Database\BaseConnection->query('SELECT cod_usuario,nombre FROM usuarios WHERE correo =\'pablo@gmail.com\' and contrasena= \'pablo\'')
 3 APPPATH\Controllers\Home.php(21): App\models\Modelo->existe('pablo@gmail.com', 'pablo')
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->comprueba()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-28 15:04:56 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'mercadilloGitan...', 3306, '', 0)
#1 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Models\Modelo.php(7): CodeIgniter\Database\BaseConnection->query('SELECT cod_usua...')
#4 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Controllers\Home.php(21): App\models\Modelo->existe('pablo@gmail.com', 'pablo')
#5 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(932): App\Controllers\Home->comprueba()
#6 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Models\Modelo.php(7): CodeIgniter\Database\BaseConnection->query('SELECT cod_usua...')
#3 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Controllers\Home.php(21): App\models\Modelo->existe('pablo@gmail.com', 'pablo')
#4 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(932): App\Controllers\Home->comprueba()
#5 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-12-28 15:04:56 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\Modelo.php(7): CodeIgniter\Database\BaseConnection->query('SELECT cod_usuario,nombre FROM usuarios WHERE correo =\'pablo@gmail.com\' and contrasena= \'pablo\'')
 3 APPPATH\Controllers\Home.php(21): App\models\Modelo->existe('pablo@gmail.com', 'pablo')
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->comprueba()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-28 15:06:06 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'mercadilloGitan...', 3306, '', 0)
#1 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Models\Modelo.php(7): CodeIgniter\Database\BaseConnection->query('SELECT cod_usua...')
#4 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Controllers\Home.php(21): App\models\Modelo->existe('pablo@gmail.com', 'pablo')
#5 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(932): App\Controllers\Home->comprueba()
#6 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Models\Modelo.php(7): CodeIgniter\Database\BaseConnection->query('SELECT cod_usua...')
#3 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Controllers\Home.php(21): App\models\Modelo->existe('pablo@gmail.com', 'pablo')
#4 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(932): App\Controllers\Home->comprueba()
#5 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-12-28 15:06:06 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\Modelo.php(7): CodeIgniter\Database\BaseConnection->query('SELECT cod_usuario,nombre FROM usuarios WHERE correo =\'pablo@gmail.com\' and contrasena= \'pablo\'')
 3 APPPATH\Controllers\Home.php(21): App\models\Modelo->existe('pablo@gmail.com', 'pablo')
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->comprueba()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-28 15:06:23 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'mercadilloGitan...', 3306, '', 0)
#1 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Models\Modelo.php(7): CodeIgniter\Database\BaseConnection->query('SELECT cod_usua...')
#4 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Controllers\Home.php(21): App\models\Modelo->existe('pablo@gmail.com', 'pablo')
#5 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(932): App\Controllers\Home->comprueba()
#6 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Models\Modelo.php(7): CodeIgniter\Database\BaseConnection->query('SELECT cod_usua...')
#3 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Controllers\Home.php(21): App\models\Modelo->existe('pablo@gmail.com', 'pablo')
#4 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(932): App\Controllers\Home->comprueba()
#5 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-12-28 15:06:23 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\Modelo.php(7): CodeIgniter\Database\BaseConnection->query('SELECT cod_usuario,nombre FROM usuarios WHERE correo =\'pablo@gmail.com\' and contrasena= \'pablo\'')
 3 APPPATH\Controllers\Home.php(21): App\models\Modelo->existe('pablo@gmail.com', 'pablo')
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->comprueba()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-28 15:15:27 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'mercadilloGitan...', 3306, '', 0)
#1 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Models\Modelo.php(7): CodeIgniter\Database\BaseConnection->query('SELECT cod_usua...')
#4 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Controllers\Home.php(21): App\models\Modelo->existe('pablo@gmail.com', 'pablo')
#5 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(932): App\Controllers\Home->comprueba()
#6 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Models\Modelo.php(7): CodeIgniter\Database\BaseConnection->query('SELECT cod_usua...')
#3 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Controllers\Home.php(21): App\models\Modelo->existe('pablo@gmail.com', 'pablo')
#4 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(932): App\Controllers\Home->comprueba()
#5 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-12-28 15:15:27 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\Modelo.php(7): CodeIgniter\Database\BaseConnection->query('SELECT cod_usuario,nombre FROM usuarios WHERE correo =\'pablo@gmail.com\' and contrasena= \'pablo\'')
 3 APPPATH\Controllers\Home.php(21): App\models\Modelo->existe('pablo@gmail.com', 'pablo')
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->comprueba()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-28 15:16:31 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'mercadilloGitan...', 3306, '', 0)
#1 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Models\Modelo.php(7): CodeIgniter\Database\BaseConnection->query('SELECT cod_usua...')
#4 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Controllers\Home.php(21): App\models\Modelo->existe('pablo@gmail.com', 'pablo')
#5 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(932): App\Controllers\Home->comprueba()
#6 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Models\Modelo.php(7): CodeIgniter\Database\BaseConnection->query('SELECT cod_usua...')
#3 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\app\Controllers\Home.php(21): App\models\Modelo->existe('pablo@gmail.com', 'pablo')
#4 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(932): App\Controllers\Home->comprueba()
#5 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\MercadilloElGitanillo\MercadilloGitanillo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-12-28 15:16:31 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\Modelo.php(7): CodeIgniter\Database\BaseConnection->query('SELECT cod_usuario,nombre FROM usuarios WHERE correo =\'pablo@gmail.com\' and contrasena= \'pablo\'')
 3 APPPATH\Controllers\Home.php(21): App\models\Modelo->existe('pablo@gmail.com', 'pablo')
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Home->comprueba()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
